version: '3.4'
services:
  mysql_node01:
    hostname: mysql_node01
    image: garutilorenzo/mysql-innodb-cluster:latest
    build:
     context: mysql/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - type: volume
        source: mysql_node01
        target: /var/lib/mysql/
        volume:
          nocopy: true
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
       cluster:
          ipv4_address: 172.16.0.2
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: test
       MYSQL_PASSWORD: P@ssw0rd
       MYSQL_DATABASE: db_test
       GROUP_NAME: C55153C1-1574-4972-BF06-7332D6AD46A7
       BOOTSTRAP: 1

  mysql_node02:
    hostname: mysql_node02
    image: garutilorenzo/mysql-innodb-cluster:latest
    build:
     context: mysql/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/replica.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - type: volume
        source: mysql_node02
        target: /var/lib/mysql/
        volume:
          nocopy: true
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
       cluster:
          ipv4_address: 172.16.0.3
    environment:
       MYSQL_ROOT_PASSWORD: root
       GROUP_NAME: C55153C1-1574-4972-BF06-7332D6AD46A7
       GROUP_SEEDS: mysql_node01:33061,mysql_node03:33061
    depends_on:
      - "mysql_node01"

  mysql_node03:
    hostname: mysql_node03
    image: garutilorenzo/mysql-innodb-cluster:latest
    build:
     context: mysql/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/replica-bis.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - type: volume
        source: mysql_node03
        target: /var/lib/mysql/
        volume:
          nocopy: true
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
       cluster:
          ipv4_address: 172.16.0.4
    environment:
       MYSQL_ROOT_PASSWORD: root
       GROUP_NAME: C55153C1-1574-4972-BF06-7332D6AD46A7
       GROUP_SEEDS: mysql_node01:33061,mysql_node02:33061
    depends_on:
      - "mysql_node01"

  router:
    hostname: router
    image: garutilorenzo/mysql-innodb-cluster-router:latest
    build:
     context: mysqlrouter/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
    restart: always
    ports:
      - "3306:3306"
      - "6606:6606"
      - "6446-6447:6446-6447"
    volumes:
      - type: volume
        source: mysql_router
        target: /var/lib/mysqlrouter
        volume:
          nocopy: true
    networks:
       cluster:
          ipv4_address: 172.16.0.5
    depends_on:
      - "mysql_node01"
      - "mysql_node02"
      - "mysql_node03"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_HOST: mysql_node01
       CLUSTERMEMBERS: 3

volumes:
 mysql_node01:
 mysql_node02:
 mysql_node03:
 mysql_router:

networks:
  cluster:
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16
